// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_cbryce996.Data;

namespace project_cbryce996.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221101180220_Init DB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("project_cbryce996.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CManufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("CModel")
                        .HasColumnType("longtext");

                    b.Property<string>("CName")
                        .HasColumnType("longtext");

                    b.Property<string>("CType")
                        .HasColumnType("longtext");

                    b.Property<string>("IPAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("MACAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("OSArch")
                        .HasColumnType("longtext");

                    b.Property<string>("OSName")
                        .HasColumnType("longtext");

                    b.Property<string>("OSVersion")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
