// <auto-generated />
using System;
using AssetManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AssetManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221121201617_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("AssetManagement.Domain.Software.SoftwareEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("SystemEntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SystemEntityId");

                    b.ToTable("SoftwareTable");
                });

            modelBuilder.Entity("AssetManagement.Domain.System.SystemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("SystemTable");
                });

            modelBuilder.Entity("AssetManagement.Domain.Software.SoftwareEntity", b =>
                {
                    b.HasOne("AssetManagement.Domain.System.SystemEntity", null)
                        .WithMany("Installs")
                        .HasForeignKey("SystemEntityId");
                });

            modelBuilder.Entity("AssetManagement.Domain.System.SystemEntity", b =>
                {
                    b.OwnsOne("AssetManagement.Domain.System.ValueObjects.IpAddress", "Ip", b1 =>
                        {
                            b1.Property<Guid>("SystemEntityId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Ip")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("SystemEntityId");

                            b1.ToTable("SystemTable");

                            b1.WithOwner()
                                .HasForeignKey("SystemEntityId");
                        });

                    b.OwnsOne("AssetManagement.Domain.System.ValueObjects.MacAddress", "Mac", b1 =>
                        {
                            b1.Property<Guid>("SystemEntityId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Mac")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("SystemEntityId");

                            b1.ToTable("SystemTable");

                            b1.WithOwner()
                                .HasForeignKey("SystemEntityId");
                        });

                    b.Navigation("Ip")
                        .IsRequired();

                    b.Navigation("Mac")
                        .IsRequired();
                });

            modelBuilder.Entity("AssetManagement.Domain.System.SystemEntity", b =>
                {
                    b.Navigation("Installs");
                });
#pragma warning restore 612, 618
        }
    }
}
