// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_cbryce996.Data;

namespace project_cbryce996.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221011141711_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("project_cbryce996.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BiosName")
                        .HasColumnType("longtext");

                    b.Property<string>("BiosVendor")
                        .HasColumnType("longtext");

                    b.Property<string>("BiosVersion")
                        .HasColumnType("longtext");

                    b.Property<string>("CpuArch")
                        .HasColumnType("longtext");

                    b.Property<string>("CpuModel")
                        .HasColumnType("longtext");

                    b.Property<string>("CpuName")
                        .HasColumnType("longtext");

                    b.Property<string>("CpuVendor")
                        .HasColumnType("longtext");

                    b.Property<string>("GpuName")
                        .HasColumnType("longtext");

                    b.Property<string>("GpuType")
                        .HasColumnType("longtext");

                    b.Property<string>("GpuVendor")
                        .HasColumnType("longtext");

                    b.Property<string>("Ip")
                        .HasColumnType("longtext");

                    b.Property<string>("MbName")
                        .HasColumnType("longtext");

                    b.Property<string>("MbVendor")
                        .HasColumnType("longtext");

                    b.Property<string>("MbVersion")
                        .HasColumnType("longtext");

                    b.Property<string>("Os")
                        .HasColumnType("longtext");

                    b.Property<string>("SystemName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
