# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    
    # Source Project
    - name: Restore Source
      run: dotnet restore
      working-directory: ./src/DesktopUI
      
    - name: Build Source
      run: dotnet build --no-restore
      working-directory: ./src/DesktopUI
    
    # Domain Tests
    - name: Restore Domain Test
      run: dotnet restore
      working-directory: ./tests/Domain/Unit
      
    - name: Build Domain Test
      run: dotnet build --no-restore
      working-directory: ./tests/Domain/Unit
      
    - name: Run Domain Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./tests/Domain/Unit
